- auth.tsx
- components/ProfileList.tsx
- components/cards/CardList.tsx
- components/cards/NumberOfCommits.tsx
- next.config.js
- package-lock.json
- package.json
- pages/index.tsx
- services/githubServices.client.tsx
- tsconfig.json
1. fixed a bug that the login page is not redirected when login failed
2. suppressed excessive requests to GitHub API
3. improved the result of GitHub's commit count to be changed according to the logged-in user
4. Improved profile information to change according to the logged-in user.
> Bug Fixes and Functional Improvements

- components/common/Login.tsx
- pages/index.tsx
> Revert "fix: Do not show index page if not authenticated"

- components/common/Login.tsx
- pages/index.tsx
> fix: Do not show index page if not authenticated

- components/common/Login.tsx
- components/common/Logout.tsx
- components/common/Sidebar.tsx
- pages/privacy-policy.tsx
- pages/terms-of-service.tsx
- pages/user-settings.tsx
There were no 'Terms of Service' and 'Privacy Policy' before.
Created them using those generators below;
- https://www.generateprivacypolicy.com/
- https://www.terms-conditions-generator.com/
Nothing special
- https://www.generateprivacypolicy.com/
- https://www.terms-conditions-generator.com/
> Added Terms of Service and Privacy Policy using those generators

- package-lock.json
- package.json
- sitemap.config.js
No sitemap.xml and robots.txt were there, so Google can't find this website properly
Added auto-generated sitemap.xml and robots.txt at build so that Google can find this site and users can search by some words for this site.
> Added auto generated sitemap.xml and robots.txt at build

- config/firebaseClient.js
Google Analytics is not aggregated. Probably due to not initializing the Analytics object provided by Firebase officially.
https://console.firebase.google.com/u/1/project/polygonhr-d5153/analytics/app/web:YzM3ZDg5YTAtY2EzYy00Zjc3LTlmM2YtNTAyN2NlNTM5Yjgx/overview/~2F%3Ft%3D1655017196174&fpn%3D872650867147&swu%3D1&sgu%3D1&sus%3Dupgraded&cs%3Dapp.m.dashboard.overview&g%3D1
I initialized the analytics object provided by the Firebase official.
Unnecessary
Nothing
https://firebase.google.com/docs/analytics/get-started?platform=web
> Activated Google Analytics for this app

- .github/pull_request_template.md
- components/buttons/DisconnectWithGithubButton.tsx
- services/getAnImageFromStorage.tsx
Some minor corrections were discovered during pull request No. 69.
- The pull request template does not have a field for description of environment variable changes, which is the cause of the error
- Arguments for some buttons are not well written
- There is an obtrusive log in the console
- Added a field in the pull request template to describe changes to environment variables.
- Improved writing of certain button arguments.
- Removed annoying console logs.
No
No
No
> Refactoring: Improved pull request template, and removed unused props and console.log

- components/buttons/DisconnectWithAsanaButton.tsx
- components/buttons/RequestOAuthButton.tsx
- components/cards/CardList.tsx
- components/cards/NumberOfCloseTasks.tsx
- components/cards/NumberOfOpenTasks.tsx
- config/firebaseTypes.ts
- pages/api/get-asana-access-token.ts
- pages/api/revoke-asana-refresh-token.ts
- pages/index.tsx
- pages/user-settings.tsx
- services/asanaServices.client.tsx
- services/setDocToFirestore.tsx
Until now, Asana's OAuth2.0 access token has not been supported. As a result, Asana's API was being used with private access tokens, forcing users to provide information that should not be shared with others.
A button to obtain Asana's OAuth2.0 access token has been added to the user settings screen. ~However, the change from the existing private access token to the OAuth2.0 access token for each of Asana's APIs will be made in the next pull request.~  => Added new commits and resolved
1. Open the User Settings page and press the 'Connect with Asana' button
2. Jump to Asana and then login with Asana
3. Authorize scopes by pressing the 'Allow' button at the bottom
4. Redirected back to the User Settings page, and in a few seconds, a message will pop up. Then press 'OK' or just Enter.
5. …
> Added a button to get Asana OAuth 2.0 access token in the user settings page

- auth.tsx
- components/cards/CardList.tsx
- pages/api/get-asana-access-token.ts
- pages/index.tsx
- pages/user-settings.tsx
- services/asanaServices.client.tsx
- services/githubServices.client.tsx
- services/setDocToFirestore.tsx
We recently supported OAuth2.0 authentication for the Asana API, but the access token expired after one hour, so error 401: Unauthorized occurred after one hour.
Added a process to ask Asana's authentication server to re-issue an access token with a refresh token and retry the API call if error 401: Unauthorized is returned when accessing the Asana API.
For Access Token;
|Before 3:30PM 6/13 2022|
|---|
|eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.----------.wfBxjQejxq0bXm6t_1qk-1jHrcb3Fy0fYo03ZNtPuAE|
|After 5:43PM 6/13 2022|
|---|
|eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.----------.SBVe4STZY1WQ_rBoJ_iQpbZiUJj2lFTUDp__5LTgI50|
For Refresh Token, it remains unchanged;
|Before 3:30PM 6/13 2022|
|---|
|1/1200781652740141:59a8e----------93ed6|
|After 5:43PM 6/13 2022|
|---| …
> Hotfix: Added process to refresh Asana's OAuth access token when it expires.

- components/cards/CardList.tsx
- components/cards/VelocityOfTaskClose.tsx
- package-lock.json
- package.json
- public/sitemap-0.xml
- services/asanaServices.client.tsx
The average weekly speed of task completion was not originally implemented. There was only the total number of completed and uncompleted for the entire period. But what we wanted to know was the speed.
Aggregation and display of average weekly task completion speeds implemented.
For mobile screens;
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/4620828/173363836-53877dc9-29ca-4413-9b51-4edd2febd6a2.png)|![image](https://user-images.githubusercontent.com/4620828/173363694-51633b5e-0ebb-423a-8352-228304adf3c9.png)|
|Before|
|---|
|![image](https://user-images.githubusercontent.com/4620828/173364080-78885880-1430-4ef0-bce6-3574f9caa0b6.png)|
|After|
|---|
|![image](https://user-images.githubusercontent.com/4620828/173364016-9a703b3b-c510-4dd9 …
> Added a new card, Velocity of closing tasks per week for Asana

- components/common/Login.tsx
- pages/_app.tsx
- pages/cancel-membership.tsx
- pages/help/how-to-get-asana-info.tsx
- pages/help/how-to-get-github-info.tsx
- pages/index.tsx
- pages/privacy-policy.tsx
- pages/terms-of-service.tsx
- pages/user-list.tsx
- pages/user-settings.tsx
As the title says, I checked the Twitter card on the production environment URL after the last pull request merges to see if it would display correctly, and it did not!
I thought the reason might be that Twitter, like Googlebot, cannot see the contents of the meta tag in the Head tag in index.tsx because it cannot log in and be authenticated, so I added it to the _app.tsx component over the authentication.
Verified with Card validator provided by Twitter;
https://cards-dev.twitter.com/validator
|Before|
|---|
|![image](https://user-images.githubusercontent.com/4620828/173489518-2fffb227-0264-4b31-bef3-775f5e4faf3a.png)|
|After|
|---|
|![image](https://user-images.githubusercontent.com/4620828/173499321-5ed4ff11-f868-4b64-94fc-8fd3effa2765.png)|
Do you require registration to the following …
> Hotfix: Fixed a bug that prevented Twitter cards from being displayed.

- components/common/Login.tsx
- config/firebaseClient.js
- firebaseAdmin.ts
The development and production environments were the same. So, needless to say, it is a dangerous situation. In addition, Asana's access token is probably managed by being tied to the client ID and client secret, so if you get an access token in the development environment, it will not work in the production environment. We need to isolate each time whether this is a bug in the source code or not, and we want to eliminate the cost of this work.
1. Separated Firebase Project for production and development environments.
2. Firebase-related environment variables in the .env.local file in the local environment were also separated into .env.production.local and .env.development.local.
3. Vercel Hosting's registration details were also corrected.
|Before|After|
|---|---| …
> Separate current Firestore environment into Production and Development for safty reason

- components/buttons/ButtonList.tsx
- components/buttons/SpecifyPeriodFixedTerm.tsx
- constants/timestampButtonList.json
- context/GlobalContextProvider.tsx
- pages/_app.tsx
For mobile screens;
|Before|After|
|---|---|
|---|---|
|Before|
|---|
|---|
|After|
|---|
|---|
Do you require registration for the following console screens beside the source code? If so, please attach evidence of registration to each of the console screens below.
- GitHub Actions: 
- Vercel Hosting: 
- Firebase Console: 
- Google Cloud Platform: 
- Asana Developer Console: 
- Slack Developer Console: 
For desktop screen,
- DOM Content Loaded Speed: x.xx (s) --> x.xx (s), -xxx (ms)
- Finish: x.xx (s) --> x.xx (s), -xxx (ms)
|Chrome Developer Console Network Tab (Before)|
|---|
|---|
|Chrome Developer Console Network Tab (After)|
|---|
|---|
> feature: Global State with Context API for data Timeframes

- pages/privacy-policy.tsx
> Revised how to use Google Calendar data in privacy-policy page

- pages/privacy-policy.tsx
- pages/terms-of-service.tsx
|Before|
|---|
|![image](https://user-images.githubusercontent.com/4620828/183704968-9450987a-67ab-4782-a7a9-0a233db10734.png)|
|After|
|---|
|![image](https://user-images.githubusercontent.com/4620828/183705079-f9e20324-13c1-4019-8811-1f49afc35eb0.png)|
|Before|
|---|
|![image](https://user-images.githubusercontent.com/4620828/183705267-33660717-1115-426e-bebc-43df787a1f74.png)|
|After|
|---|
|![image](https://user-images.githubusercontent.com/4620828/183705329-5a8f38f0-1673-41fa-b7e4-70a1b40fa29c.png)|
> Unified with other pages about background color and padding on both sides.

- components/buttons/SpecifyPeriodFixedTerm.tsx
- components/cards/CardListForJira.tsx
- constants/timestampButtonList.json
- public/sitemap-0.xml
1. Period search function has last 1 year and last 1 month, but no in-between
1. The most recent 6 months and the most recent 3 months were added to the period search function.
> Fixed Jira undefined bug and Added periods of time, last 6 months and last 3 months

- pages/_app.tsx
1. OGP image is no longer new
1. Updated OGP photo image with the latest GIF
> Updated OGP photo image with a latest GIF

- pages/_app.tsx
> Revert "Replaced ogp photo link"

- pages/_app.tsx
> Revert "Updated OGP photo image with a latest GIF"

- config/firebaseTypes.ts
- pages/charts/slack.tsx
- services/slackServices.client.ts
1. cannot be written because its size 4,941,778 exceeded the maximum allowed size of 1,048,576 bytes
1. Reduced the size of data I save into firestore
- [When do we get this error from firestore "A document cannot be written because it exceeds the maximum size allowed."](https://stackoverflow.com/questions/68358500/when-do-we-get-this-error-from-firestore-a-document-cannot-be-written-because-i)
> Hotfix: Reduced the size of data due to firestore max size limit per a document

- components/cards/CardListForSlack.tsx
- pages/api/search-slack-mentioned.ts
- pages/api/search-slack-new-sent.ts
- pages/api/search-slack-replies.ts
- pages/api/search-slack-sent.ts
1. Regarding the Slack numbers, there was a bug that sometimes caused the numbers to change.
https://www.loom.com/share/9776789aaab34fc5b9ecc4c992edbc56
1. Added a process to not update the Slack numbers if they fall below 0
https://www.loom.com/share/8fd28b40a84044759a73b8097b61ad39
> Added a process to not update the Slack numbers if they fall below 0
