- components/common/Login.tsx
- components/common/Logout.tsx
If a user already signed in this app with google account, then the user would try to sign in with github account, then this error happen and the sign in process would fail.
With this PR, a user can link second OAuth account with first OAuth account, without any errors.
https://drive.google.com/open?id=1B9ofzSO06aryfPsEmG57L0yOVzlzcGs9&authuser=nishio.hiroshi%40suchica.com&usp=drive_fs
https://firebase.google.com/docs/auth/web/account-linking
https://firebase.google.com/docs/reference/js/auth.md#linkwithpopup
https://firebase.google.com/docs/auth/web/google-signin#expandable-1 * A little bit outdated I think.
And removed unnecessary reload functions.
> Resolved firebase auth error: auth/account-exists-with-different-credential

- auth.tsx
- components/common/Login.tsx
- pages/index.tsx
Normally firebase automatically updates its token, but with getServerSideProps, it runs before client side rendering, so it might use expired token because automatic updates by getIdToken() can only run in client side.
This continuously occur every 1 hour, so it needs to be fixed asap.
1. User settings page worked
2. logout button worked
3. login button worked
One point, an error now occurs when the network is disconnected. This will be addressed as a separate issue.
https://colinhacks.com/essays/nextjs-firebase-authentication
https://stackoverflow.com/questions/65261134/firebase-authentication-token-expiration-with-next-js-ssr
> Resolved firebase error: auth/id-token-expired every 1 hour in getServerSideProps

- components/common/Login.tsx
- firebaseAdmin.ts
- package.json
Vercel preview page says that;
> The current domain is not authorized for OAuth operations. This will prevent signInWithPopup, signInWithRedirect, linkWithPopup and linkWithRedirect from working. Add your domain (workstats-5erzshygc-workstats.vercel.app) to the OAuth redirect domains list in the Firebase console -> Auth section -> Sign in method tab.
After registering above, then this error occurred;
> 'Failed to parse private key: Error: Invalid PEM formatted message.'
Applied this solution;
https://github.com/gladly-team/next-firebase-auth/discussions/95
Confirmed this changes worked well with vercel preview page!!
Nothing
https://github.com/gladly-team/next-firebase-auth/discussions/95
> Added console.log to examine an error which occurs only in production environment.

- components/buttons/ButtonList.tsx
- components/buttons/SpecifyPeriodFixedTerm.tsx
- components/buttons/SpecifyPeriodFromTo.tsx
- components/buttons/SpecifyPeriodLastWeek.tsx
- components/cards/NumberOfPullRequests.tsx
Originally, we had only prepared a view with buttons for period selection, etc., and it was not in working condition. Since we finally released the web app to the public, I couldn't just leave it there.
I left the view itself in a state where all periods were selected and no other periods could be selected.
No
No
> Disabled a function to specify period of terms for production env

- .github/pull_request_template.md
- components/buttons/ButtonList.tsx
- components/buttons/SpecifyPeriodFixedTerm.tsx
- components/buttons/SpecifyPeriodFromTo.tsx
- components/buttons/SpecifyPeriodLastWeek.tsx
- components/cards/NumberOfPullRequests.tsx
- components/common/Sidebar.tsx
'Contact Us' button in sidebar was not working, and it led users to 404 page.
Enabled 'Contact Us' button in sidebar to open a mailer like Gmail in a new tab.
I really wanted to create markdown-like headings for the body content as well, but I didn't know how to do it, so I decided not to set any body in particular.
No
> Enabled 'Contact Us' button in sidebar

- package.json
- public/robots.txt
- public/sitemap-0.xml
- public/sitemap.xml
- sitemap.config.js
Could not open https://workstats.dev/sitemap.xml and it gave me a 404 page.
Changed output directory setting in sitemap.config.js because ./out directory is for `next export` which is used for only static web applications.
sitemap pages were successfully displayed this time.
> Resolved mis-configuration for sitemap location

- components/boxes/InputBox.tsx
- components/buttons/ConnectWithGithub.tsx
- components/buttons/DisconnectWithGithubButton.tsx
- components/buttons/SubmitButton.tsx
- components/cards/NumberOfCommits.tsx
- components/common/Logout.tsx
- config/firebaseTypes.ts
- pages/api/get-github-access-token.ts
- pages/index.tsx
- pages/user-settings.tsx
- public/sitemap-0.xml
- services/githubServices.client.tsx
- services/setDocToFirestore.tsx
OAuth for GitHub was not implemented. Therefore, use of the GitHub API was limited to public repositories, and the frequency of use was also limited.
A "Connect with GitHub" button has been added to the user settings screen. A "Disconnect with GitHub" button was also added to allow users to disconnect from GitHub after connecting with it.
Follow the user operation procedures and put up evidence photos.
1. Open the User Settings page and press the "Connect with GitHub" button. 
2. A GitHub sign-in page will open OR an agreement screen will appear asking if you agree to grant these permissions to WorkStats on behalf of the signed-in GitHub user. Agree with this.
3. You will be redirected to the user settings page. At this time, the "Connect with GitHub" button will automatically switch to …
> Added "Connect with GitHub" button to use GitHub access token on behalf of users and viceversa

- components/cards/CardList.tsx
- components/cards/NumberOfCommits.tsx
- components/cards/NumberOfPullRequests.tsx
- components/cards/NumberOfReview.tsx
- pages/index.tsx
- pages/user-settings.tsx
- public/sitemap-0.xml
- services/githubServices.client.tsx
Previously, there was no authentication, so only information from public repositories could be obtained. This limited the number of target users.
A process was created in the previous pull request for a user to perform OAuth authentication and grant specific permissions to WorkStats. The access token obtained there was added to the three API headers on GitHub. This has made it possible to retrieve information on private repositories and, although unconfirmed, has probably greatly improved the maximum number of times the API can be used.
A repository I had previously created as a sample was used for testing. It is in a private state.
In user settings, configure this private repository in repository 1.
Numbers in private repositories are aggregated.
Nothing
How to use Access Token; …
> Enabled GitHub APIs to access private repositories

- components/common/Login.tsx
As the title suggests, sometimes there are cases where user documentation is not created. The reproducible conditions are difficult to figure out.
The only place to create user documentation is in the login component, so that is the only possible cause. After looking at the source, I guessed that this phenomenon might occur when the reload in the next line finishes first, without waiting for the Promise that the user document creation is completed.
Nothing special
Nothing special
Nothing special
> Hotfix: Fixed a bug that sometimes prevented user documents from being created.

- components/buttons/ProductHunt.tsx
- components/common/Login.tsx
- next.config.js
Most of the users are now via Product Hunt. But when they transition from there, the login page does not state that this application is listed on Product Hunt. So, we believe that users are uncertain whether they can log in or not.
I learned that there was a badge provided by Product Hunt, so I inset it.
|Before|After|
|--|--|
|![image](https://user-images.githubusercontent.com/4620828/172910311-f189a888-16ba-4f5d-af18-0d6840760132.png)|![image](https://user-images.githubusercontent.com/4620828/172910206-d64fe34c-4a59-461e-8edc-3417672b77cc.png)|
|Before|
|--|
|![image](https://user-images.githubusercontent.com/4620828/172910248-c6db3db1-17c9-40af-a780-5d166e49eba5.png)|
|After|
|![image](https://user-images.githubusercontent.com/4620828/172910082-29e89245-1ec6-4334-ba9a-d19aad8400ec.png)| …
> Added Product Hunt jump button to login component to reassure users as much as possible

- pages/index.tsx
Under certain conditions, an error occurs when a new user opens the top dashboard or user settings screen.
I have not been able to reproduce the error under certain conditions, but I have encountered it myself from time to time.
I didn't implement it because I don't know how to use optional chains in the case of arrays. Since this is the direct cause of the problem, I implemented an optional chain.
No evidence is required as it occurred during work on pull request No. 69 and was corrected and confirmed during the process.
No
No
> Hotfix: Under certain conditions, the app fails to access user document when a new user joins

- config/firebaseClient.js
- firebaseAdmin.ts
The upper limit on the size of environment variables that can be registered in the console with Vercel Hosting is 4kb, but it was just barely enough. If it exceeds the limit, we will not be able to deploy.
The solution itself is provided by Vercel in two ways: one is to Encrypt and Decrypt, which I have read carefully and the implementation itself is not that complicated, but it is more complicated to operate and manage. For example, if we encrypt environment variables related to Firebase, specifically if we later want to change the Auth Domain to the correct name, we have to encrypt it again. That is a special procedure that I would prefer not to do.
Therefore, I decided to write the environment variables directly in the source code, which would not cause much of a problem even if they …
> Reduced size of environment variables which is not secrets

- components/cards/CardList.tsx
- components/cards/EstimatedDateOfTaskEnd.tsx
- components/cards/VelocityOfTaskClose.tsx
- services/asanaServices.client.tsx
Although the average weekly speed of task completion was available, users had to calculate by hand when all of their current tasks would be completed if they estimated at that speed. Users can calculate the approximate completion date in their minds, but if the date is clearly stated, they will have more time to think about whether the date is good or bad.
Added a card to show the estimated completion date for Asana to solve the problem.
For mobile screen;
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/4620828/173511480-51ce9a52-ca16-4ebd-9074-eb9c82b55bdc.png)|![image](https://user-images.githubusercontent.com/4620828/173511069-6c353405-3bd7-410f-b882-e55310ebfb20.png)|
|Before|
|---| …
> Added a card to show estimated completion date for Asana

- components/cards/CardList.tsx
- components/cards/VelocityOfTaskClose.tsx
- services/asanaServices.client.tsx
- services/setDocToFirestore.tsx
There was an error where if the first decimal place in the average weekly speed of the number of tasks completed was 0, that 0 would disappear. I noticed that 8.0 happened to be 8, as shown in the screenshot. This may be confusing to you, but to the user, it is not visually obvious whether 8.4 was rounded to 8, 7.6 was rounded to 8, or 8.0 became 8!
While correcting the problem, we noticed other minor errors that needed to be addressed.
The toFixed method was used to solve the problem.
|Before|
|---|
|![image](https://user-images.githubusercontent.com/4620828/173828302-15cf874c-fee9-46aa-9bb0-8bddbc4d7f69.png)|
|After|
|---|
|![image](https://user-images.githubusercontent.com/4620828/173828363-53daa20d-417e-4efe-98f6-5badc899e49c.png)|
Do you require registration to …
> Fixed an error in which if the first decimal place of a speed was 0, the 0 would be lost.

- components/buttons/DisconnectWithSlack.tsx
- config/firebaseTypes.ts
- firebaseAdmin.ts
- pages/api/get-asana-access-token.ts
- pages/api/get-slack-access-token.ts
- pages/api/revoke-asana-refresh-token.ts
- pages/api/revoke-slack-refresh-token.ts
- pages/index.tsx
- pages/user-settings.tsx
- public/sitemap-0.xml
- services/asanaServices.client.tsx
- services/setDocToFirestore.tsx
- services/slackServices.client.ts
Until now, the linkage between Slack and WorkStats has been through user tokens. This meant that integration was only possible within the workspace in which the WorkStats app was currently registered, and could not be used in other workspaces. In other words, Slack data aggregation was virtually unusable.
WorkStats now supports OAuth2.0 provided by Slack. This allows WorkStats to be used in any workspace. In addition, users can now simply click the "Integrate with Slack" button and configure the necessary settings for integration without having to do any research.
Do you require registration to the following console screens other than the source code? If so, please attach evidence of registration to each of the console screens below.
- GitHub Actions: Necessary
- …
> Supported Slack OAuth 2.0

- components/cards/CardList.tsx
- components/cards/NumberOfMentioned.tsx
- pages/api/search-slack.ts
- pages/index.tsx
- services/githubServices.client.tsx
- services/slackServices.client.ts
- services/slackServices.server.tsx
Since the Slack API violates CORS constraints and causes an error if not called from the server-side, Slack-related aggregation was done on the server-side at request time, but the calculation time is long. Therefore, the start of rendering is slow. I didn't know how to solve this problem at the time. This can be solved by using Next/API, which allows the server-side program to run after rendering.
We solved the Slack API CORS constraint by wrapping the Slack API in Next/API and calling that Next/API from the browser.
There are several Slack-related functions, but we first solved one simple one.
|Before|
|---|
|![image](https://user-images.githubusercontent.com/4620828/175917573-e7c46d4a-b4e2-471a-9472-9e7dd031cece.png)|
|After|
|---| …
> Changed the timing of tallying number of mentioned from the time of request to after the render.

- .github/pull_request_template.md
- .gitignore
- components/cards/CardList.tsx
- components/cards/NumberOfCommits.tsx
- components/cards/NumberOfPullRequests.tsx
- components/cards/NumberOfReview.tsx
- config/firebaseTypes.ts
- pages/cancel-membership.tsx
- pages/index.tsx
- pages/user-settings.tsx
- services/getDocFromFirestore.ts
- services/githubServices.client.tsx
- services/setDocToFirestore.tsx
This is not limited to GitHub, but the system was initially designed to tally the numbers after each render and re-render and display them later. This caused two problems: for example, even numbers that had just been calculated took a long time to appear because they had to be calculated again when reloaded. The problem became more pronounced when a button was implemented to change the aggregation period in the future.
As the title says, I changed to store aggregated GitHub numbers in Firestore and display those values on the first render.
|Before|
|---|
|![image](https://user-images.githubusercontent.com/4620828/177025915-77f48ec2-4abb-4ffe-aadb-ec7b7e71508a.png)|
|After|
|---|
|![image](https://user-images.githubusercontent.com/4620828/177025953-da39fb9a-4ae2-42d4-8a …
> Changed to store aggregated GitHub numbers in Firestore and display those values on first render

- components/cards/CardList.tsx
- services/asanaServices.client.tsx
The Asana API access token expires in one hour. Therefore, when the API is called after expiration, a 401 error is returned, in which case there is a process to refresh the token. However, in fact, we had implemented a process to update the DB with the refreshed access token and call the API again with the new access token, but we had not used the return value.
Returns were added.
|Before|
|---|
|<img width="960" alt="image" src="https://user-images.githubusercontent.com/4620828/177039334-1cd4f9b3-bc83-46aa-a90f-754110eab15f.png">|
|After|
|---|
|![image](https://user-images.githubusercontent.com/4620828/177039353-b7760721-9549-47db-819f-89e79d0b0c6b.png)|
Do you require registration for the following console screens beside the source code? If so, please attach …
> Hotfilx: Fixed a bug that the numbers were once set to 0 when the Asana API access token expired after 1 hour.

- components/cards/CardList.tsx
- components/common/Login.tsx
- pages/index.tsx
- services/setDocToFirestore.tsx
If you have a new table, during development, you inevitably create a record in that table with the ID of the logged-in user. Then I forgot to take care of the new user, which would originally require creating a new table or record for a new user. As a result, the following error occurred.
The above error was addressed. Specifically, the Numbers table is now created when a user logs in.
For mobile screens;
|Before (For a new user)|
|---|
|![image](https://user-images.githubusercontent.com/4620828/177042269-1e392e20-f014-43c1-9af0-926f4c45744f.png)|
|After (For a new user)|
|---|
|![image](https://user-images.githubusercontent.com/4620828/177042326-8f30b744-cab7-48f8-9aca-98bc6bb0195f.png)|
Do you require registration for the following console screens beside the source …
> Hotfix: Fixed a bug that caused an error for new users due to a new table.

- pages/_app.tsx
There has been a bug ever since it was implemented that prevented Twitter card images from being displayed, but the cause of this bug has not been found until now.
https://betterprogramming.pub/add-a-twitter-card-to-your-website-69f7d53b68a8
This site shows that the Google Drive link is possible, but apparently the URL had to be converted. I did not know that. I don't know if this will solve the problem, but I'll give it a try.
https://syncwithtech.blogspot.com/p/direct-download-link-generator.html
I replaced it with the converted URL as the site says.
It did not work in the official simulator provided by Twitter, but it worked in real Twitter. We use this as evidence.
No
No
No
No
No
> Fixed that Twitter card is unable to show its image

- auth.tsx
- pages/cancel-membership.tsx
- pages/dashboard.tsx
- pages/user-settings.tsx
The old problem came back with the creation of the homepage: you know that Firebase's authentication expires after an hour, and because of that, you get a 500 error (Internal Server Error) after an hour if you access the site directly from your browser's favorites. At this time, reloading will fix the problem.
Other than that, a new bug has been created. The newly created home page (<Component /> to be precise) is not wrapped in auth.tsx (<AuthProvider> to be precise) and can be entered without being logged in.
So, while this page is open, the mechanism in auth.tsx to force re-authentication once every 10 minutes does not work. As a result, even in this case, I get a 500 error after an hour. And reloading does not fix it. This is quite a problem.
The error location is here. Once the …
> Temporary workaround for 500 error due to Firebase token expiring in 1 hour.

- components/onboarding/product-tour.tsx
1. Tour on the dashboard screen does not transition to the user settings page after completion of the tour
2. As a result, I'm guessing, there are likely to be cases where users leave the site without knowing what to do next
1. After touring the dashboard, open the user settings page forcefully
https://www.loom.com/share/0929251a66164af0b2568ab66c53df47
> After touring on the dashboard, open the user settings page

- components/buttons/RequestGoogleOAuthButton.tsx
- components/buttons/RequestOAuthButton.tsx
- components/cards/CardListForAsana.tsx
- components/cards/CardListForGithub.tsx
- components/cards/CardListForGoogleCalendar.tsx
- components/cards/CardListForJira.tsx
- components/cards/CardListForSlack.tsx
- pages/user-settings.tsx
1. The gear icon on the dashboard screen allows you to jump to the user settings page, but it takes you to the top of the page. This is assumed to reduce user attention and cause users to leave the site.
2. After moving to the user settings page, users are not sure what to do, and we assume that they are leaving the site, and do not intuitively know if they should press the API linkage button.
1. Enabled hashtags on user-settings page
3. Pulsed linkage button when API not linked.
https://www.loom.com/share/c0181606d2ea4cf395b76dd1ed2e8121
- https://github.com/vercel/next.js/issues/11109
> Enabled hashtags on user settings page and pulsed linkage button when API not linked.

- components/user-settings/SettingsForAsana.tsx
- components/user-settings/SettingsForAtlassian.tsx
- components/user-settings/SettingsForGitHub.tsx
- components/user-settings/SettingsForGoogle.tsx
- components/user-settings/SettingsForSlack.tsx
1. There was no explanation of API integration on the user settings page.
2. There was a help page, but users had to open a separate tab, which was a bit time-consuming.
3. As a result, we assume that users are not reassured, causing them to leave the site.
1. Added explanations and notes for each API linkage.
> Added notes in user settings page

- components/cards/CardListForSlack.tsx
1. This Week" does not work well on Sundays
2. On Sunday, "Since" and "Until" dates are the same, but I actually tried the same thing in Slack's desktop app and couldn't get a good search
3. Specifically, for Sunday, October 9, 2022, "Since" and "Until" should be October 9, respectively, but for some reason the search range changes to October 8 - October 10
1. If "Since" and "Until" are the same date, add one day to the "Until" date.
2. This only occurs when using "This Week" on Sunday
Sunday ended while I was working on it, so I can no longer leave evidence, I'll use the Slack desktop app evidence as an alternative.
> Hotfix: Slack numbers in this week does not work on Sunday

- pages/_app.tsx
1. GIF was not available for OGP
1. Replace the GIF file with the latest photo file
> Replaced ogp photo link

- services/slackServices.client.ts
1. Slack's search API call limit is 20 calls per minute
2. The maximum number of retrieval cases per API call is 100
3. So, for example, if a user replies more than 2,000 times, an error will occur.
4. In fact, in a production environment, an error occurred for a user
1. When calling the API more than 20 times, added a process to wait 1 minute for every 20 calls.
- [Rate Limits](https://api.slack.com/docs/rate-limits#tier_t2)
- [Remainder (%)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Remainder)
> Hotfix: Supported API rate limit for slack chart page

- pages/charts/slack.tsx
1. Slack search will be unstable after 10,000 results
1. so we will assume 2 years for now.
> Hotfix: Slack search will be unstable after 10,000 results, so we will assume 2 years for now.
